_SAMPLE_PREDICTIONS = [
    "brick work in cement and sand 1:8 in 9\" thick external walls - ground floor (bsr f02)",
    "preparing and painting new wood work with one coat primer and two coats enamel paint (bsr m17)",
    "mild steel reinforcement - first floor (bsr e02)",
    "shuttering for floor slab in 15mm thick plywood up to 11'-0\" soffit height supported by props (bsr d05)",
    "allow for provision of performance security (1% of contract sum)",
    "supplying and fixing plastic 1/2\" swan-neck tap - s-lon brand - kitchen sink (bsr t18)",
    "cement concrete 1:3:6 (1 1/2\") in wall foundations including placing and compacting (bsr c01)",
    "brick work in cement and sand 1:8 in foundation up to dpc level (bsr f01)",
    "removing top soil manually to depth not exceeding 6\" and removing all debris away from site (bsr b02)",
    "brick work in cement and sand 1:5 in 4 1/2\" thick internal partition walls - ground floor (bsr f05)",
    "supplying and fixing 1 1/4\" dia. upvc conduit pipe (bsr v124)",
    "pvc eaves gutter 4 1/2\" square type fixed with pvc brackets @ 1'-6\" c/c including mitre joints, gutter joiners, running heads and end caps (bsr r01)",
    "shuttering for lintels in 12mm thick plywood boards including dismantling (bsr d12)",
    "shuttering for sides of foundation with 15mm thick plywood board including dismantling (bsr d02)",
    "supplying and fixing polished brass hinges 4\"x2 1/2\" thickness 4.0mm - windows (bsr p34)",
    "skirting 4\"x1/2\" thick in cement and sand 1:3 projected or flush to walls finished with cement slurry floating including forming groove - ground floor (bsr j08)",
    "painting all external walls with one coat of exterior wall primer including surface preparation (bsr m02)",
    "5/8\" thick plastering to plinth wall in cement sand 1:3 including finishing with cement slurry floating (bsr k01)",
    "asbestos roofing close fitting ridges fixed complete with roofing screws or hook bolts (bsr q04)",
    "supply and fix chromium plated soap tray - standard quality (bsr s56, pc rs.1,500)",
    "shuttering for columns including dismantling using pre-fabricated steel shutter halves (bsr d09)",
    "supply and fix chromium plated soap holder - rocell brand (bsr s30)",
    "door frame 3 3/4\"x2 3/4\" in approved timber supplying and fixing in position - all doors (bsr n12)",
    "river sand supplying, spreading, laying and compacting in foundation trenches - measured on compacted volume (bsr b27)",
    "anti-termite treatment for new construction with biflexthrine 10tc - horizontal and vertical barriers with 10-year warranty, measured on plinth area (bsr b41)",
    "light point wired through 10a one gang one-way plate switch using 2x1/1.13mm pvc insulated copper wire in fully concealed/surface pvc conduits (bsr v01)",
    "roof covering with corrugated asbestos roofing sheets - timber frame work and ridge covering measured separately (bsr q02)",
    "painting all internal walls with one coat of emulsion paint - single coat budget finish (bsr m03)",
    "window frame 3 3/4\"x2 3/4\" in approved timber supplying and fixing in position - all windows (bsr n18)",
    "supplying and fixing polished brass hinges 4\"x3\" thickness 4.2mm weight not less than 310g - all doors (bsr p35)",
    "3/4\" thick dpc in cement sand 1:3 finished with 2 coats of dpc tar, blinded with sand - ground floor (bsr j01)",
    "allow for provision of advance payment security",
    "supplying and wiring 2x2.5mm2 cu/pvc/pvc cable + 2.5mm2 earth wire excluding conduit (bsr v70)",
    "light points wired through 10a two gang one-way plate switch in pvc conduits (bsr v02)",
    "shuttering for stiffener columns in 12mm thick plywood between wall panels in 9\" and 4 1/2\" walls (bsr d13)",
    "supply and fix chromium plated toilet paper holder - rocell brand (bsr s34)",
    "shuttering for columns in 15mm thick plywood with side supports and props (bsr d08)",
    "shuttering for floor beams in 15mm thick plywood up to 12'-0\" soffit height supported by props (bsr d06)",
    "supplying and fixing 4\" dia. 89 deg swept bend (bsr t159)",
    "supplying and fixing rim lock - union brand model j1445 or approved equivalent - main entrance door (bsr p07)",
    "supply and fix chromium plated pillar tap (cold water) for wash basin - rocell brand (bsr s22)",
    "pvc down pipes 3 1/2\" dia. fixed to wall with pvc clips @ 4'-0\" c/c including sockets, bends and elbows (bsr r02)",
    "shuttering for sides of foundation with 1\" thick rubber planking including dismantling (bsr d01)",
    "supply and fix chromium plated robe hook - rocell brand (bsr s33)",
    "tor steel reinforcement to slabs, beams, lintels, columns and footings - bent to shape, laid in position and tied with 16 bwg annealed binding wire - ground floor (bsr e04)",
    "supply and fix bidet spray - chromium plated, rocell brand (bsr s18)",
    "transport of soil 25m to 100m by any means including loading and unloading (bsr b34)",
    "supplying and fixing 1/2\" dia. pvc compact ball valve - isolation (bsr t25)",
    "supply and fix chromium plated towel ring - rocell brand (bsr s32)",
    "fan regulator wired through 10a one gang one-way switch in fully concealed pvc conduits (bsr v49)",
    "g.i. flashing 20 bwg 1'-6\" girth - wall and verge abutments pointed with polyurethane sealant including three coats synroof hi-build waterproofing paint (bsr q19)",
    "brick work in cement and sand 1:8 in 9\" thick external walls - first floor (bsr f03)",
    "flush mounted 13a switch socket outlet wired in fully concealed pvc conduits - radial circuit feeding 4 sockets (bsr v41)",
    "plastering 5/8\" thick to all internal walls in cement and sand 1:5 finished semi-rough with wooden float - ground floor (bsr k03)",
    "racking and cutting at hipped roof ends (bsr q07)",
    "supply and fix plastic seat cover for water closet - standard quality (bsr s53, pc rs.2,400)",
    "painting all internal walls with one coat of interior wall primer (bsr m01)",
    "staircase work",
    "clearing site vegetation manually including removal of bushes, shrubs and rubbish up to 30'-0\" distance (bsr b01)",
    "supplying and fixing 1 1/2\" dia. upvc waste pipe type 600 - basin waste (bsr t41)",
    "3/4\"-1\" upvc conduits laying in slab including binding wire to draw through (bsr v121)",
    "supplying and fixing single lever mortice door lock - union brand model 678.24.95 or approved equivalent (bsr p04)",
    "plastering 5/8\" thick to all external walls in cement and sand 1:5 finished semi-rough - ground floor (bsr k03)",
    "shuttering for sides of plinth beams and ground beams on top of foundation in 15mm thick plywood including dismantling (bsr d03)",
    "supply and fixing 20mmx5mmx12\" long flat iron bracket @ 2'-0\" c/c for fixing valance/barge board - two coats anti-corrosive paint included (bsr q33)",
    "volume batched grade 25 concrete prepared at site using mixer and vibrator - ground floor columns, plinth beams and tie beams (bsr c04)",
    "750 gauge polythene damp proof membrane with 6\" laps laid under floors - ground floor (bsr j02)",
    "preparing and painting new wood work with one coat of primer and two coats enamel paint - all timber doors and window frames (bsr m17)",
    "brick steps 1'-1 1/2\" in brick cement and sand 1:5, finished with 1/2\" thick rendering with cement slurry including 6\" high foundation (bsr f09)",
    "brick work in cement and sand 1:5 in 4 1/2\" thick internal partition walls - first floor (bsr f06)",
]


def get_sample_model_a_predictions() -> list[str]:
    return list(_SAMPLE_PREDICTIONS)
