"""add category model

Revision ID: 0c0283135947
Revises: 0001
Create Date: 2026-04-26 22:53:07.207227

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c0283135947'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bsr_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_no', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('work_type', sa.Text(), nullable=True),
    sa.Column('material_type', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('constraints', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_no')
    )
    op.create_index('ix_bsr_items_category', 'bsr_items', ['category'], unique=False)
    op.create_index('ix_bsr_items_item_no', 'bsr_items', ['item_no'], unique=False)
    op.create_index('ix_bsr_items_work_type', 'bsr_items', ['work_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bsr_items_work_type', table_name='bsr_items')
    op.drop_index('ix_bsr_items_item_no', table_name='bsr_items')
    op.drop_index('ix_bsr_items_category', table_name='bsr_items')
    op.drop_table('bsr_items')
    # ### end Alembic commands ###
