"""add_estimate_lifecycle_fields

Revision ID: 19705ab1bf8f
Revises: 0002_add_users_estimates
Create Date: 2026-05-11 14:53:00.256854

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19705ab1bf8f'
down_revision = '0002_add_users_estimates'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('wizard_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('estimates', sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('estimates', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('estimates', sa.Column('regenerated_from_estimate_id', sa.UUID(), nullable=True))
    op.add_column('estimates', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_estimates_regenerated_from_estimate_id'), 'estimates', ['regenerated_from_estimate_id'], unique=False)
    op.create_foreign_key(None, 'estimates', 'estimates', ['regenerated_from_estimate_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estimates', type_='foreignkey')
    op.drop_index(op.f('ix_estimates_regenerated_from_estimate_id'), table_name='estimates')
    op.drop_column('estimates', 'cancelled_at')
    op.drop_column('estimates', 'regenerated_from_estimate_id')
    op.drop_column('estimates', 'error_message')
    op.drop_column('estimates', 'progress')
    op.drop_column('estimates', 'wizard_payload')
    # ### end Alembic commands ###
